Implement API rate limiting
jellyfin/jellyfin-plugin-anilist pull request #79
Opened 2024-10-04 04:07 UTC by HansLehnert

2024-10-04 07:09 UTC, Shadowghost commented
If this is a rework of the current feature you might want to keep the config key the same, otherwise you'd get crashed on updated plugin installations

2024-10-05 02:53 UTC, HansLehnert commented
> If this is a rework of the current feature you might want to keep the config key the same, otherwise you'd get crashed on updated plugin installations

I couldn't reproduce. Seems like extra elements in the configuration xml document just get ignored when loading it? Issue is that the default value for the current config key was set too high.

2025-08-17 16:14 UTC, TehNut commented
Hi, could this please be revisited soon? Users of this plugin constantly top the list of blocked user agents by a huge margin.

2026-04-28 14:16 UTC, nielsvanvelzen commented
Currently AniList has blocked Jellyfin from using their API for not implementing rate limiting. This PR should solve the problem. I can't add the server team for review in a plugin repo so pinging @jellyfin/server for visibility.

2026-04-28 14:36 UTC, JPVenson requested changes

2026-04-28 14:36 UTC, JPVenson commented on Jellyfin.Plugin.AniList/Providers/AniList/AniListAnimeImageProvider.cs
> -
We generally do not use primary constructors

2026-04-28 14:36 UTC, JPVenson commented on Jellyfin.Plugin.AniList/Providers/AniList/AniListAnimeImageProvider.cs
> +            HttpClient httpClient = httpClientFactory.CreateClient();
please use var instead

2026-04-28 14:36 UTC, JPVenson commented on Jellyfin.Plugin.AniList/Providers/AniList/AniListApi.cs
> +    public class AniListApi(IHttpClientFactory httpClientFactory, ILogger<AniListApi> logger)
same

2026-04-28 14:36 UTC, JPVenson commented on Jellyfin.Plugin.AniList/PluginServiceRegistrator.cs
> +        int maxConcurrency = configurationManager.Configuration.LibraryScanFanoutConcurrency;
i dont think thats a good idea, the scanner is already limited to that i dont see a benefit doing that here additionally 0 of that value means processor core count which you did not handle either

2026-04-29 01:30 UTC, HansLehnert commented on Jellyfin.Plugin.AniList/PluginServiceRegistrator.cs
> +        int maxConcurrency = configurationManager.Configuration.LibraryScanFanoutConcurrency;
I don't like this much either, but the reason is that these .NET rate limiters require specifying a maximum amount of queued requests... Otherwise, we can probably implement this with a simple semaphore instead of the rate limiters.

> additionally 0 of that value means processor core count which you did not handle either

this is handled right below

2026-04-29 05:16 UTC, JPVenson commented on Jellyfin.Plugin.AniList/PluginServiceRegistrator.cs
> +        int maxConcurrency = configurationManager.Configuration.LibraryScanFanoutConcurrency;
oh yea i dont know how i overlooked that lol.

I mean rate limiting is in this case a function over time not a simple concurrency limit so it doesn't really matter how many parallel requests we make as long as that timeframe per number of requests is not exceeded. IIRC anidb has a burst and a longer term window restriction.

2026-04-29 08:53 UTC, daspositioned commented on Jellyfin.Plugin.AniList/PluginServiceRegistrator.cs
> +        int maxConcurrency = configurationManager.Configuration.LibraryScanFanoutConcurrency;
I've mentioned this in the Discord/Matrix but AniList also has a 4 request/second burst rate limit

2026-05-04 07:07 UTC, HansLehnert commented on Jellyfin.Plugin.AniList/PluginServiceRegistrator.cs
> +        int maxConcurrency = configurationManager.Configuration.LibraryScanFanoutConcurrency;
I removed that queue limit calculation, and replaced with a big enough value. Also did some improvements to the rate limiter so that there will be actual concurrency. There's two rate limiters now, first one limits, the api requests per minute and second one limits bursts within one second. It works reliably, from what I could test.

2026-05-04 07:15 UTC, HansLehnert commented on Jellyfin.Plugin.AniList/Providers/AniList/AniListAnimeImageProvider.cs
> -
I reverted it, but I'm curious why

2026-05-04 17:17 UTC, nielsvanvelzen commented
We went with the slightly simpler PR at #112 for now so we can get a fix out for the blocking, but feel free to rebase this one.

2026-09-10 23:01 UTC, closed without merging